server.port=8081
jwt.secret=5hG7kL9pQ2rT8vX4zB1nC3fD6wE7yU0q

# ===========================
#  DATABASE CONFIG
# ===========================
spring.datasource.url=jdbc:postgresql://localhost:5432/playground
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# ===========================
#  JPA / HIBERNATE
# ===========================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===========================
#  SQL INIT
# ===========================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
